trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'my-image-repository'
  azureContainerRegistry: 'my-azure-container-registry'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        imageName: '$(azureContainerRegistry).azurecr.io/$(imageRepository):$(tag)'
        containerRegistry: 'my-azure-container-registry'
        tags: |
          $(tag)
